# Generated by Django 2.2.6 on 2019-10-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizen_registration_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=500)),
                ('created_datetime', models.DateTimeField(verbose_name='created timestamp')),
            ],
        ),
    ]
